from datetime import datetime, timedelta
from typing import Any, Union, Optional
from jose import jwt, JWTError
from passlib.context import CryptContext
from src.shared.config import settings

pwd_context = CryptContext(schemes=["argon2"], deprecated="auto")

ALGORITHM = "HS256"

def create_access_token(subject: Union[str, Any], expires_delta: Optional[timedelta] = None) -> str:
    """Encode JWT with subject (use registered user email so it can serve as unique user_id app-wide)."""
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(
            minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES
        )
    to_encode = {"exp": expire, "sub": str(subject)}
    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

def decode_access_token(token: str) -> Optional[str]:
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[ALGORITHM])
        return payload.get("sub")
    except JWTError:
        return None

def verify_password(plain_password: str, hashed_password: str) -> bool:
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

from fastapi import Cookie, Header

def get_current_user_from_cookie(access_token: Optional[str] = Cookie(None)) -> Optional[str]:
    """Extract current user from JWT in cookie. Returns decoded subject (email). Used for page auth."""
    if not access_token:
        return None
    return decode_access_token(access_token)


def get_current_user_email(
    access_token: Optional[str] = Cookie(None),
    authorization: Optional[str] = Header(None),
) -> Optional[str]:
    """
    Auth dependency: extract authenticated user's email from JWT (cookie or Bearer).
    This email is used as the unique user_id across the app (DB fields, sessions, uploads).
    Why email as user_id: single source of truth from registration; no separate ID to sync;
    improves consistency with auth and avoids default/autogenerated IDs.
    """
    # API clients: Authorization: Bearer <token>
    if authorization and authorization.startswith("Bearer "):
        token = authorization[7:].strip()
        email = decode_access_token(token)
        if email:
            return email
    # Browser: cookie set at login
    if access_token:
        return decode_access_token(access_token)
    return None
