from typing import Optional
from src.auth_service.domain.interfaces import AuthRepositoryInterface
from src.auth_service.domain.entities import User
from src.auth_service.api.schemas import UserCreate, UserLogin, Token
from src.shared.security import get_password_hash, verify_password, create_access_token
from src.auth_service.application.validators import validate_password_strength

class AuthService:
    def __init__(self, repository: AuthRepositoryInterface):
        self.repository = repository


    def register_user(self, user_create: UserCreate) -> User:
        # Validate password strength
        validate_password_strength(user_create.password)

        existing_user = self.repository.get_by_email(user_create.email)
        if existing_user:
            raise ValueError("Email already registered")
        
        hashed_password = get_password_hash(user_create.password)
        new_user = User(
            email=user_create.email,
            hashed_password=hashed_password,
            is_active=True
        )
        return self.repository.create(new_user)

    def login_user(self, user_login: UserLogin) -> Optional[Token]:
        user = self.repository.get_by_email(user_login.email)
        if not user or not verify_password(user_login.password, user.hashed_password):
            return None
        # Use email as JWT subject so it serves as unique user_id app-wide (DB, sessions, uploads).
        # Improves consistency: one identifier from registration, no default/autogenerated IDs to sync.
        access_token = create_access_token(subject=user.email)
        return Token(access_token=access_token, token_type="bearer")
